# Generated by Django 4.2.1 on 2023-06-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('posicion', models.CharField(max_length=50)),
                ('equipo', models.CharField(max_length=50)),
            ],
        ),
    ]
